apiVersion: v1
kind: ConfigMap
metadata:
    name: promtail-config
    namespace: default
data:
    config.yaml: |
        server:
          http_listen_port: 3100
          grpc_listen_port: 9096

        positions:
          filename: /tmp/positions.yaml

        clients:
          - url: http://loki:3100/loki/api/v1/push

        scrape_configs:

          - job_name: kubernetes-pods
            pipeline_stages:
            - docker: {}
            kubernetes_sd_configs:
            - role: pod
            relabel_configs:
            - source_label: __meta_kubernetes_pod_annotation_prometheus_io_scrape
              action: keep
              regex: true
            - source_label: __meta_kubernetes_pod_annotation_loki_grafana_com_inject
              action: keep
              regex: true
            - source_label: __meta_kubernetes_pod_container_name
              target_label: container
            - source_label: __meta_kubernetes_pod_name
              target_label: pod
            - source_label: __meta_kubernetes_namespace
              target_label: namespace
            - source_label: __meta_kubernetes_pod_label_app
              target_label: app
