apiVersion: v1
kind: ConfigMap
metadata:
    name: prometheus-server-conf
    namespace: monitoring
data:
    prometheus.yml: |
        global:
          scrape_interval: 15s
          evaluation_interval: 15s
        scrape_configs:
          - job_name: 'kube-state-metrics'
            static_configs:
              - targets: ['kube-state-metrics.kube-system.svc.cluster.local:8080']
          - job_name: 'node'
            static_configs:
              - targets: ['node-exporter.monitoring.svc.cluster.local:9100']
