# name: CI

# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     branches:
#       - main

# jobs:
#   build-and-test:
#     runs-on: ubuntu-latest
#     container:
#       image: node:latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2
#       - name: Install dependencies
#         run: npm install
#       - name: Start development server
#         run: npm run dev &
#       - name: Run Vitest tests
#         run: npm run test date.utils.test.ts user.utils.test.ts

name: Build & Push docker image
on:
    push:
        branches:
            - main
jobs:
    build-and-push:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Set up Docker buildx
              uses: docker/setup-buildx-action@v1

            - name: Log in to Github container registry
              uses: docker/login-action@v1
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.PAT }}

            - name: Convert repository owner to lowercase
              id: lowercase
              run: echo "::set-output name=owner::$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')"

            - name: Convert repository name to lowercase
              id: repo-lowercase
              run: echo "::set-output name=repo::$(echo ${{ github.event.repository.name }} | tr '[:upper:]' '[:lower:]')"

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v1

            - name: Build and push Docker image
              uses: docker/build-push-action@v2
              with:
                  context: .
                  push: true
                  platforms: linux/amd64,linux/arm64
                  tags: ghcr.io/${{ steps.lowercase.outputs.owner }}/${{ steps.repo-lowercase.outputs.repo }}:latest
